[package]
name = "robyn"
version = "0.4.1"
authors = ["Sanskar Jethi <sansyrox@gmail.com>"]
edition = "2018"
description = "A web server that is fast!"
license = "MIT"
homepage = "https://github.com/sansyrox/robyn"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "robyn"
crate-type = ["cdylib", "rlib"]

[dependencies.pyo3]
version = "0.13.2"
features = ["extension-module"]

[patch.crates-io]
pyo3 = {git = "https://github.com/PyO3/pyo3/",branch = "main", features = ["extension-module"]}

[dependencies.pyo3-asyncio]
version = "0.13.3"
features =["tokio-runtime"]

[dependencies]
tokio = { version = "1.7.0", features = ["full"] }
dashmap = "4.0.2"
flume = "0.10.7"
httparse = "1.4.1"
hyper = { version="0.14.9", features = ["full"]}
futures = "0.3.15"

[package.metadata.maturin]
name = "robyn"
