[tool.poetry]
name = "robyn"
version = "0.6.0"
description = ""
authors = ["Sanskar Jethi <sansyrox@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
watchdog = "^2.1.3"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[project]
name = "robyn"
dependencies = [
  "watchdog>=2.1.3,<3"
]
