[tool.poetry]
name = "robyn"
version = "0.7.1"
description = "A web server that is fast!"
authors = ["Sanskar Jethi <sansyrox@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
watchdog = "^2.1.3"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[project]
name = "robyn"
dependencies = [
  "watchdog>=2.1.3,<3",
  "uvloop>=0.16.0,<0.16.1",
  "multiprocess>=0.70.12.2,<0.70.12.3"
]
