[tool.poetry]
name = "robyn"
version = "0.29.0"
description = "A web server that is fast!"
authors = ["Sanskar Jethi <sansyrox@gmail.com>"]
repository = "https://github.com/sansyrox/robyn"
documentation = "https://robyn.tech/"
classifiers = [
  "Development Status :: 3 - Alpha",
  "Environment :: Web Environment",
  "Intended Audience :: Developers",
  "License :: OSI Approved :: BSD License",
  "Operating System :: OS Independent",
  "Topic :: Internet :: WWW/HTTP",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.7",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: Implementation :: CPython",
]

[tool.poetry.urls]
"Bug Tracker" = "https://github.com/sansyrox/robyn/issues"
Changelog = "https://github.com/sansyrox/robyn/blob/main/CHANGELOG.md"

[tool.poetry.dependencies]
python = "^3.8"
maturin = "0.14.12"
watchdog = "2.2.1"
multiprocess = "0.70.14"
nestd = "0.3.1"
uvloop = { version = "0.17.0", markers = "sys_platform == 'darwin' or platform_machine == 'aarch_64' or platform_machine == 'x86_84' or platform_machine == 'i686'" }
jinja2 = { version = "3.0.1", optional = true }

[tool.poetry.extras]
templating = ["jinja2"]

[tool.poetry.group.dev]
optional = true

[tool.poetry.group.dev.dependencies]
ruff = "0.0.240"
black = "23.1"
isort = "5.12"
pre-commit = "3.0.4"
commitizen = "2.40"

[tool.poetry.group.test]
optional = true

[tool.poetry.group.test.dependencies]
requests = "2.28.2"
pytest = "7.2.1"
websocket-client = "1.5.0"
pytest-codspeed = "1.2.2"

[tool.poetry.scripts]
devserver = { callable = "integration_tests.base_routes:main" }

[build-system]
requires = ["maturin>=0.14,<0.15"]
build-backend = "maturin"

[tool.ruff]
line-length = 160
exclude = ["src/*" , ".git" , "docs"]

[tool.ruff.mccabe]
max-complexity = 10

[tool.maturin]
module-name = "robyn"
