[build-system]
requires = ["maturin>=0.12,<0.13"]
build-backend = "maturin"

[project]
name = "robyn"
version = "0.37.0"
description = "A High-Performance, Community-Driven, and Innovator Friendly Web Framework with a Rust runtime."
authors = [{ name = "Sanskar Jethi", email = "sansyrox@gmail.com" }]
repository = "https://github.com/sparckles/robyn"
documentation = "https://robyn.tech/"
dependencies = [
  'watchdog == 2.2.1',
  'multiprocess == 0.70.14',
  'nestd == 0.3.1',
# conditional
  "uvloop>=0.17.0; sys_platform == 'darwin' and platform_machine == 'aarch_64' and platform_machine == 'x86_64' and platform_machine == 'i686'"
  ]
classifiers = [
  "Development Status :: 3 - Alpha",
  "Environment :: Web Environment",
  "Intended Audience :: Developers",
  "License :: OSI Approved :: BSD License",
  "Operating System :: OS Independent",
  "Topic :: Internet :: WWW/HTTP",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.7",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: Implementation :: CPython",
]

[tool.poetry]
name = "robyn"
version = "0.37.0"
description = "A High-Performance, Community-Driven, and Innovator Friendly Web Framework with a Rust runtime."
authors = ["Sanskar Jethi <sansyrox@gmail.com>"]
repository = "https://github.com/sparckles/robyn"
documentation = "https://robyn.tech/"
classifiers = [
  "Development Status :: 3 - Alpha",
  "Environment :: Web Environment",
  "Intended Audience :: Developers",
  "License :: OSI Approved :: BSD License",
  "Operating System :: OS Independent",
  "Topic :: Internet :: WWW/HTTP",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.7",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: Implementation :: CPython",
]

[project.urls]
Issues = "https://github.com/sparckles/robyn/issues"

[tool.poetry.urls]
"Bug Tracker" = "https://github.com/sparckles/robyn/issues"
Changelog = "https://github.com/sparckles/robyn/blob/main/CHANGELOG.md"

[tool.poetry.dependencies]
python = "^3.7"
maturin = "0.14.12"
watchdog = "2.2.1"
multiprocess = "0.70.14"
nestd = "0.3.1"
uvloop = { version = "0.17.0", markers = "sys_platform == 'darwin' and platform_machine == 'aarch_64' and platform_machine == 'x86_64' and platform_machine == 'i686'" }
jinja2 = { version = "3.0.1", optional = true }

[tool.poetry.extras]
templating = ["jinja2"]

[tool.poetry.group.dev]
optional = true

[tool.poetry.group.dev.dependencies]
ruff = "0.0.240"
black = "23.1"
isort = "5.11.5"
pre-commit = "2.21.0"
commitizen = "2.40"

[tool.poetry.group.test]
optional = true

[tool.poetry.group.test.dependencies]
requests = "2.28.2"
pytest = "7.2.1"
websocket-client = "1.5.0"
pytest-codspeed = "1.2.2"

[tool.poetry.scripts]
test_server = { callable = "integration_tests.base_routes:main" }

[tool.ruff]
line-length = 160
exclude = ["src/*", ".git", "docs"]

[tool.ruff.mccabe]
max-complexity = 10

[tool.maturin]
module-name = "robyn"
