blank_issues_enabled: true
contact_links:
  - name: Discord Community Support
    url: https://discord.gg/rkERZ5eNU8
    about: You can ask and answer questions here.
  - name: Documentation
    url: https://https://sparckles.github.io/Robyn/#/
    about: The Robyn documentation.
